openapi: 3.0.0
info:
  title: ASM API v3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v3/login:
    post:
      summary: Log in and generate an ASM Token
      tags:
        - Authentication
      responses:
        '200':
          description: OK
      operationId: post-v3-login
      description: Log in and generate an OAuth Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas: {}
