openapi: 3.0.0
info:
  title: ASM API v3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v3/login:
    post:
      summary: Log in and generate an ASM Token
      tags: []
      responses: {}
      operationId: post-v3-login
components:
  schemas: {}
